name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: part 2 quick check 1
      id: part-2-quick-check-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: part 2 quick check 1
        setup-command: gcc -o part2_main.out *part2_main.c
        command: ./part2_main.out "[1.3, 2.4, 4.2, 5.0]" "[3, 4, 5, 6]"
        input: ''
        expected-output: The Cov of two input arrays is 2.15, and their own Var are
          2.83 and 1.67.
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: part 2 quick check 2
      id: part-2-quick-check-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: part 2 quick check 2
        setup-command: gcc -o part2_main.out *part2_main.c
        command: ./part2_main.out "[1.3, 2.4, 4.2, 5]" "[3.00, 4.00, 5, 6.0]"
        input: ''
        expected-output: The Cov of two input arrays is 2.15, and their own Var are
          2.83 and 1.67.
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: part 2 quick check 3
      id: part-2-quick-check-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: part 2 quick check 3
        setup-command: gcc -o part2_main.out *part2_main.c
        command: ./part2_main.out "[1.3, 2.4, 4.2, 5]" "[3, 4, -5, 6]"
        input: ''
        expected-output: The Cov of two input arrays is -1.10, and their own Var are
          2.83 and 23.33.
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PART-2-QUICK-CHECK-1_RESULTS: "${{steps.part-2-quick-check-1.outputs.result}}"
        PART-2-QUICK-CHECK-2_RESULTS: "${{steps.part-2-quick-check-2.outputs.result}}"
        PART-2-QUICK-CHECK-3_RESULTS: "${{steps.part-2-quick-check-3.outputs.result}}"
      with:
        runners: part-2-quick-check-1,part-2-quick-check-2,part-2-quick-check-3
